name: Release-Build-Publish

on:
  push:
    branches:
      - 'hddcoin'
      - '!master'
    tags:
      - '*'

jobs:
 build:
    name: Build
    strategy:
      fail-fast: false
      matrix:
        node-version: [ 16.x ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]

    runs-on: ${{ matrix.os }}
    
    steps:
      - run: echo "Hello tag ${{ github.ref }}"
